"""Adiciona modelo de Pagamento e campos de forma de pagamento na Venda

Revision ID: 8d42f8fcf5eb
Revises: 
Create Date: 2025-04-10 13:36:45.593961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d42f8fcf5eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pagamento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo_venda', sa.String(), nullable=False),
    sa.Column('forma', sa.String(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estoque',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('data_entrada', sa.DateTime(), nullable=False),
    sa.Column('numero_nota_fiscal', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venda',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('frete_cep', sa.String(length=9), nullable=True),
    sa.Column('frete_logradouro', sa.String(), nullable=True),
    sa.Column('frete_numero', sa.Integer(), nullable=True),
    sa.Column('frete_complemento', sa.String(), nullable=True),
    sa.Column('frete_bairro', sa.String(), nullable=True),
    sa.Column('frete_cidade', sa.String(), nullable=True),
    sa.Column('frete_uf', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venda')
    op.drop_table('estoque')
    op.drop_table('produto')
    op.drop_table('pagamento')
    # ### end Alembic commands ###
